export const projects = [
  {
    id: "liberty",
    slug: "liberty",
    name: "ЖК Liberty",
    nameShort: "Liberty",
    image: "/images/hero-building.jpg",
    address: "г. Кокшетау, Акмолинская область",
    floors: 9,
    sections: 3,
    totalApartments: 108,
    apartments: "1–3 комнатные",
    finishing: "Чистовая отделка",
    ceilingHeight: "2,7 м",
    area: "42–98 м²",
    pricePerSqm: "от 350 000 ₸",
    status: "Строится" as const,
    statusNote: "Сдача 4 кв. 2026",
    class: "Комфорт",
    construction: "Монолитно-каркасная",
    parking: "Наземный, гостевой",
    heating: "Центральное",
    elevator: "Пассажирский",
    walls: "Кирпич",
    facade: "Облицовочный кирпич",
    territory: "Закрытый двор, детская площадка, видеонаблюдение",
    windows: "Увеличенные оконные проёмы",
    description:
      "ЖК Liberty — современный жилой комплекс комфорт-класса от D Capital в Кокшетау. 9-этажный дом из 3 секций с чистовой отделкой. Квартиры от 42 до 98 м² с продуманными планировками для комфортной жизни. Закрытый двор с детской площадкой и круглосуточным видеонаблюдением.",
    features: [
      "Комфорт-класс с чистовой отделкой",
      "9 этажей, 3 секции, 108 квартир",
      "Монолитно-каркасная технология",
      "Кирпичные стены с утеплением",
      "Облицовочный кирпичный фасад",
      "Увеличенные оконные проёмы",
      "Закрытый двор с видеонаблюдением",
      "Центральное отопление",
    ],
    infrastructure: [
      "Развитая инфраструктура района",
      "Школы и детские сады — в шаговой доступности",
      "Общественный транспорт — рядом",
      "Магазины и ТЦ — поблизости",
    ],
  },
  {
    id: "houses",
    slug: "houses",
    name: "Частные дома",
    nameShort: "Дома",
    image: "/images/dostar.jpg",
    address: "г. Кокшетау и пригород",
    floors: 2,
    sections: 1,
    apartments: "Индивидуальные проекты",
    finishing: "Чистовая отделка",
    ceilingHeight: "2,7–3 м",
    area: "120–250 м²",
    pricePerSqm: "от 280 000 ₸",
    status: "Строится" as const,
    statusNote: "Принимаем заказы",
    class: "Комфорт",
    construction: "Кирпичная / монолитно-каркасная",
    parking: "Гараж",
    heating: "Центральное / автономное",
    elevator: "—",
    walls: "Кирпич / газоблок",
    facade: "Облицовочный кирпич",
    territory: "Собственный участок",
    description:
      "D Capital строит частные дома в Кокшетау и пригороде. От идеи до ключей — берём на себя всё: проектирование, строительство и чистовую отделку. Дома площадью от 120 до 250 м² с индивидуальными планировками, качественными материалами и современным дизайном.",
    features: [
      "Строительство «под ключ» — от проекта до отделки",
      "Индивидуальные и типовые проекты",
      "Качественные материалы и технологии",
      "Площадь от 120 до 250 м²",
      "Гараж и собственный участок",
      "Чистовая отделка",
      "Современный дизайн фасадов",
      "Гарантия качества от D Capital",
    ],
    infrastructure: [
      "Удобное расположение в черте города или пригороде",
      "Подключение ко всем коммуникациям",
      "Транспортная доступность",
    ],
  },
]

export const floorPlans = [
  // ЖК Liberty — планировки
  { id: 1, projectSlug: "liberty", projectName: "ЖК Liberty", rooms: 1, area: 42.0, price: 14700000, pricePerSqm: 350000, image: "https://storage.googleapis.com/bd-kz-01/layouts-v2/340x340/150891.jpg" },
  { id: 2, projectSlug: "liberty", projectName: "ЖК Liberty", rooms: 1, area: 48.5, price: 16975000, pricePerSqm: 350000, image: "https://storage.googleapis.com/bd-kz-01/layouts-v2/340x340/161816.jpg" },
  { id: 3, projectSlug: "liberty", projectName: "ЖК Liberty", rooms: 2, area: 62.0, price: 21700000, pricePerSqm: 350000, image: "https://storage.googleapis.com/bd-kz-01/layouts-v2/340x340/110033.jpg" },
  { id: 4, projectSlug: "liberty", projectName: "ЖК Liberty", rooms: 2, area: 68.3, price: 23905000, pricePerSqm: 350000, image: "https://storage.googleapis.com/bd-kz-01/layouts-v2/340x340/150891.jpg" },
  { id: 5, projectSlug: "liberty", projectName: "ЖК Liberty", rooms: 3, area: 82.0, price: 28700000, pricePerSqm: 350000, image: "https://storage.googleapis.com/bd-kz-01/layouts-v2/340x340/161816.jpg" },
  { id: 6, projectSlug: "liberty", projectName: "ЖК Liberty", rooms: 3, area: 98.0, price: 34300000, pricePerSqm: 350000, image: "https://storage.googleapis.com/bd-kz-01/layouts-v2/340x340/110033.jpg" },
]

export const mortgagePrograms = [
  {
    id: "baspana-hit",
    name: "Баспана Хит",
    rate: 5,
    maxTerm: 25,
    downPayment: 20,
    description: "Государственная ипотечная программа с льготной ставкой для приобретения первичного жилья.",
  },
  {
    id: "7-20-25",
    name: "7-20-25",
    rate: 7,
    maxTerm: 25,
    downPayment: 20,
    description: "Программа доступного жилья: 7% годовых, 20% первоначальный взнос, на 25 лет.",
  },
  {
    id: "nauryz",
    name: "Наурыз",
    rate: 3.5,
    maxTerm: 25,
    downPayment: 20,
    description: "Льготная ипотечная программа с минимальной ставкой для социально уязвимых категорий.",
  },
  {
    id: "nauryz-zhumysker",
    name: "Наурыз Жумыскер",
    rate: 4,
    maxTerm: 25,
    downPayment: 20,
    description: "Программа для работающих граждан с привлекательной процентной ставкой.",
  },
]

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("ru-KZ").format(price) + " ₸"
}
