export const projects = [
  {
    id: "atlant",
    slug: "atlant",
    name: "ЖК ATLANT",
    nameShort: "ATLANT",
    image: "/images/hero-building.jpg",
    address: "ул. Рахимбека Сабатаева, 77А, Кокшетау",
    floors: 9,
    sections: 4,
    apartments: "1–4 комнатные",
    finishing: "Улучшенная черновая",
    ceilingHeight: "3.0 м",
    status: "В продаже" as const,
    statusNote: "Сдача в 2025",
    class: "Комфорт+",
    construction: "Кирпичная",
    parking: "Наземный/Подземный",
    heating: "Центральное",
    elevator: "Бесшумные скоростные лифты",
    walls: "Кирпич",
    facade: "Облицовочный кирпич/HPL-панели",
    territory: "Детская площадка, закрытый двор, видеонаблюдение",
    description:
      "ЖК ATLANT — это флагманский проект Estet Stroy в самом центре Кокшетау. Современная архитектура, продуманные планировки и высокое качество строительства. ЖК ATLANT предлагает жилье премиум-качества по доступным ценам.",
    features: [
      "Класс Комфорт+",
      "Панорамные окна",
      "Кирпичная технология",
      "Закрытый безопасный двор",
      "Центральное отопление",
    ],
    area: "42–110 м²",
    pricePerSqm: "от 335 000 ₸",
    infrastructure: [
      "Центр города",
      "Школы и детские сады в шаговой доступности",
      "Парковая зона рядом",
    ],
  },
  {
    id: "lumiere",
    slug: "lumiere",
    name: "ЖК LUMIERE",
    nameShort: "LUMIERE",
    image: "/images/hero-building.jpg",
    address: "ул. Рахимбека Сабатаева, 77А, Кокшетау",
    floors: 10,
    sections: 2,
    totalApartments: 80,
    apartments: "2–4 комнатные",
    finishing: "Предчистовая отделка",
    ceilingHeight: "3.2 м",
    area: "55–130 м²",
    status: "В продаже" as const,
    statusNote: "Сдача в 2026",
    class: "Бизнес",
    construction: "Монолитно-каркасная",
    parking: "Подземный паркинг",
    heating: "Центральное",
    walls: "Газоблок с шумоизоляцией",
    facade: "Вентилируемый фасад",
    territory: "Консьерж-сервис, закрытый двор, ландшафтный дизайн",
    description:
      "LUMIERE — это воплощение изысканности и комфорта. Элитный жилой комплекс с уникальной архитектурой и панорамным остеклением, созданный для тех, кто ценит эстетику в каждой детали.",
    features: [
      "Бизнес-класс",
      "Высота потолков 3.2 метра",
      "Дизайнерские холлы",
      "Подземный паркинг с лифтом",
    ],
    pricePerSqm: "По запросу",
    infrastructure: [
      "Элитный район",
      "Развитая коммерческая инфраструктура",
    ],
  },
  {
    id: "keremet",
    slug: "keremet",
    name: "ЖК KEREMET",
    nameShort: "KEREMET",
    image: "/images/hero-building.jpg",
    address: "г. Кокшетау",
    floors: 5,
    sections: 3,
    apartments: "1–3 комнатные",
    finishing: "Сдано",
    ceilingHeight: "2.8 м",
    status: "Сдан" as const,
    statusNote: "Продажи завершены",
    class: "Комфорт",
    construction: "Кирпичная",
    parking: "Гостевой",
    heating: "Центральное",
    walls: "Кирпич",
    facade: "Облицовочный кирпич",
    territory: "Детская площадка",
    description:
      "ЖК KEREMET — успешно реализованный проект компании Estet Stroy. Уютный 5-этажный дом с развитой придомовой территорией и качественными коммуникациями.",
    features: [
      "Кирпичный дом",
      "Удачное расположение",
      "Надежные коммуникации",
    ],
    area: "38–92 м²",
    pricePerSqm: "Продано",
    infrastructure: [
      "Тихий район",
      "Школа рядом",
    ],
  },
  {
    id: "private-houses",
    slug: "private-houses",
    name: "Частные дома",
    nameShort: "Дома",
    image: "/images/hero-building.jpg",
    address: "Кокшетау и пригород",
    floors: 2,
    sections: 1,
    apartments: "Индивидуальные проекты",
    finishing: "Под ключ / Черновая",
    ceilingHeight: "3.0 м",
    status: "Строится" as const,
    statusNote: "Принимаем заказы",
    class: "Индивидуальный",
    construction: "Любая",
    parking: "Собственный гараж/участок",
    heating: "Автономное",
    walls: "Кирпич/Газоблок/Сип-панели",
    facade: "Любой вид отделки",
    territory: "Собственный участок",
    description:
      "Estet Stroy занимается строительством не только многоквартирных жилых комплексов, но и индивидуальных жилых домов. Мы поможем вам построить дом вашей мечты от проектирования до сдачи под ключ.",
    features: [
      "Индивидуальное проектирование",
      "Качественные материалы",
      "Гарантия на работы",
      "Соблюдение сроков",
    ],
    area: "от 100 м²",
    pricePerSqm: "от 250 000 ₸",
    infrastructure: [
      "Помощь в выборе участка",
      "Подключение коммуникаций",
    ],
  },
]

export const floorPlans = [
  { id: 1, projectSlug: "atlant", projectName: "ЖК ATLANT", rooms: 2, area: 62.45, price: 20920750, pricePerSqm: 335000, image: "/images/hero-building.jpg" },
  { id: 2, projectSlug: "atlant", projectName: "ЖК ATLANT", rooms: 3, area: 88.30, price: 29580500, pricePerSqm: 335000, image: "/images/hero-building.jpg" },
  { id: 3, projectSlug: "lumiere", projectName: "ЖК LUMIERE", rooms: 2, area: 59.99, price: 27000000, pricePerSqm: 450000, image: "/images/hero-building.jpg" },
  { id: 4, projectSlug: "lumiere", projectName: "ЖК LUMIERE", rooms: 4, area: 125.0, price: 56250000, pricePerSqm: 450000, image: "/images/hero-building.jpg" },
]

export const mortgagePrograms = [
  {
    id: "otau",
    name: "Отау",
    rate: 9,
    maxTerm: 19,
    downPayment: 20,
    description: "Специальная ипотечная программа от Отбасы банка. Ставка 9% годовых.",
  },
  {
    id: "7-20-25",
    name: "7-20-25",
    rate: 7,
    maxTerm: 25,
    downPayment: 20,
    description: "Программа доступного жилья от КФУ для первичного рынка.",
  },
  {
    id: "installment",
    name: "Рассрочка",
    rate: 0,
    maxTerm: 2,
    downPayment: 30,
    description: "Беспроцентная рассрочка от застройщика Estet Stroy.",
  },
]

export function formatPrice(price: number | string): string {
  if (typeof price === "string") return price
  return new Intl.NumberFormat("ru-KZ").format(price) + " ₸"
}
