export const projects = [
  {
    id: "ak-shanyraq",
    slug: "ak-shanyraq",
    name: "ЖК «Ак Шанырак»",
    nameShort: "Ак Шанырак",
    image: "/images/ak-shanyraq.jpg",
    address: "Центральная часть Кокшетау",
    floors: 9,
    apartments: "1–3 комнатные",
    finishing: "Черновая отделка",
    ceilingHeight: "3 м",
    status: "Сдан" as const,
    class: "Комфорт",
    description:
      "9-этажная новостройка в центральной части Кокшетау. Индивидуальный архитектурный проект с обширным остеклением. Квартиры от 1 до 3 комнат с черновой отделкой, что позволяет реализовать любые дизайнерские решения.",
    features: [
      "Индивидуальный архитектурный проект",
      "Обширное панорамное остекление",
      "Центральное расположение",
      "Развитая инфраструктура района",
      "Детская площадка во дворе",
      "Подземная парковка",
    ],
    infrastructure: [
      "Школы и детские сады — 5 мин",
      "Торговые центры — 7 мин",
      "Парки и скверы — 3 мин",
      "Остановки общественного транспорта — 2 мин",
      "Медицинские учреждения — 10 мин",
    ],
  },
  {
    id: "baitas",
    slug: "baitas",
    name: "ЖК BAITAS",
    nameShort: "BAITAS",
    image: "/images/baitas.jpg",
    address: "ул. Малика Габдуллина, 4, Кокшетау",
    floors: 9,
    apartments: "1–3 комнатные",
    finishing: "Предчистовая отделка",
    ceilingHeight: "3 м",
    status: "Сдан" as const,
    class: "Комфорт",
    description:
      "Жилой комплекс BAITAS по адресу ул. Малика Габдуллина, 4. Современный дом с продуманными планировками и качественными материалами строительства. Удобное расположение с развитой инфраструктурой.",
    features: [
      "Кирпичное строительство",
      "Высота потолков 3 метра",
      "Предчистовая отделка",
      "Благоустроенная придомовая территория",
      "Видеонаблюдение",
      "Современные лифты",
    ],
    infrastructure: [
      "Школы — 5 мин пешком",
      "Магазины и супермаркеты — 3 мин",
      "Общественный транспорт — 2 мин",
      "Поликлиника — 7 мин",
      "Центральный парк — 10 мин",
    ],
  },
  {
    id: "dostar",
    slug: "dostar",
    name: "ЖК DOSTAR",
    nameShort: "DOSTAR",
    image: "/images/dostar.jpg",
    address: "ул. Свердлова, 1, Кокшетау",
    floors: 9,
    apartments: "1–3 комнатные",
    finishing: "Предчистовая отделка",
    ceilingHeight: "3 м",
    status: "Строится" as const,
    class: "Комфорт",
    description:
      "Жилой комплекс DOSTAR — это 9-этажный кирпичный дом по ул. Свердлова, 1. Высота потолков 3 метра, предчистовая отделка. Идеальный выбор для семей, ценящих тишину и комфорт.",
    features: [
      "Кирпичный дом",
      "9 этажей",
      "Высота потолков 3 метра",
      "Предчистовая отделка",
      "Малоквартирность — тишина и уют",
      "Закрытый двор",
    ],
    infrastructure: [
      "Образовательные учреждения — 5 мин",
      "Продуктовые магазины — 2 мин",
      "Остановки транспорта — 3 мин",
      "Спортивные объекты — 10 мин",
      "Медицинские центры — 8 мин",
    ],
  },
]

export const apartments = [
  { id: 1, projectSlug: "ak-shanyraq", projectName: "ЖК «Ак Шанырак»", rooms: 1, floor: 3, area: 42.5, price: 14500000 },
  { id: 2, projectSlug: "ak-shanyraq", projectName: "ЖК «Ак Шанырак»", rooms: 1, floor: 5, area: 44.0, price: 15200000 },
  { id: 3, projectSlug: "ak-shanyraq", projectName: "ЖК «Ак Шанырак»", rooms: 2, floor: 2, area: 65.3, price: 21800000 },
  { id: 4, projectSlug: "ak-shanyraq", projectName: "ЖК «Ак Шанырак»", rooms: 2, floor: 7, area: 68.0, price: 23500000 },
  { id: 5, projectSlug: "ak-shanyraq", projectName: "ЖК «Ак Шанырак»", rooms: 3, floor: 4, area: 85.2, price: 29000000 },
  { id: 6, projectSlug: "ak-shanyraq", projectName: "ЖК «Ак Шанырак»", rooms: 3, floor: 8, area: 90.0, price: 31500000 },
  { id: 7, projectSlug: "baitas", projectName: "ЖК BAITAS", rooms: 1, floor: 2, area: 40.0, price: 13500000 },
  { id: 8, projectSlug: "baitas", projectName: "ЖК BAITAS", rooms: 1, floor: 6, area: 43.5, price: 14800000 },
  { id: 9, projectSlug: "baitas", projectName: "ЖК BAITAS", rooms: 2, floor: 3, area: 62.0, price: 20500000 },
  { id: 10, projectSlug: "baitas", projectName: "ЖК BAITAS", rooms: 2, floor: 5, area: 66.8, price: 22000000 },
  { id: 11, projectSlug: "baitas", projectName: "ЖК BAITAS", rooms: 3, floor: 4, area: 82.0, price: 27500000 },
  { id: 12, projectSlug: "baitas", projectName: "ЖК BAITAS", rooms: 3, floor: 9, area: 88.5, price: 30000000 },
  { id: 13, projectSlug: "dostar", projectName: "ЖК DOSTAR", rooms: 1, floor: 2, area: 41.0, price: 13000000 },
  { id: 14, projectSlug: "dostar", projectName: "ЖК DOSTAR", rooms: 1, floor: 7, area: 45.0, price: 14500000 },
  { id: 15, projectSlug: "dostar", projectName: "ЖК DOSTAR", rooms: 2, floor: 3, area: 63.5, price: 20000000 },
  { id: 16, projectSlug: "dostar", projectName: "ЖК DOSTAR", rooms: 2, floor: 6, area: 67.0, price: 21500000 },
  { id: 17, projectSlug: "dostar", projectName: "ЖК DOSTAR", rooms: 3, floor: 5, area: 84.0, price: 27000000 },
  { id: 18, projectSlug: "dostar", projectName: "ЖК DOSTAR", rooms: 3, floor: 8, area: 91.0, price: 30500000 },
]

export const mortgagePrograms = [
  {
    id: "baspana-hit",
    name: "Баспана Хит",
    rate: 5,
    maxTerm: 25,
    downPayment: 20,
    description: "Государственная ипотечная программа с льготной ставкой для приобретения первичного жилья.",
  },
  {
    id: "7-20-25",
    name: "7-20-25",
    rate: 7,
    maxTerm: 25,
    downPayment: 20,
    description: "Программа доступного жилья: 7% годовых, 20% первоначальный взнос, на 25 лет.",
  },
  {
    id: "nauryz",
    name: "Наурыз",
    rate: 3.5,
    maxTerm: 25,
    downPayment: 20,
    description: "Льготная ипотечная программа с минимальной ставкой для социально уязвимых категорий.",
  },
  {
    id: "nauryz-zhumysker",
    name: "Наурыз Жумыскер",
    rate: 4,
    maxTerm: 25,
    downPayment: 20,
    description: "Программа для работающих граждан с привлекательной процентной ставкой.",
  },
]

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("ru-KZ").format(price) + " ₸"
}
